runtime: nodejs18

env_variables:
  LINE_ACCESS_TOKEN: "EW+GPaNwSUuhrj3btZXrACSP/5xGSk5Rg5mm/F8giRH74SEhVuHnnKhfQryfN/h8Xxe4NZfXIC0gp3XU22jEzWWTqa7zYNQVpg616Cx/9yFkzRsOe0NZzw69c0q8hLN+LMO8HGbkxLc+RiDFGJn8LAdB04t89/1O/w1cDnyilFU="
  CWB_API_KEY: "CWA-3FF8CDE5-0749-41D7-9F8B-68DD11C537A4"
  GOOGLE_MAPS_API_KEY: "AIzaSyDSwpa6gDUGBJDC8l5Sm1PvV5s2z2yd2fI"

instance_class: F1
